### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jampueroc** [mitrefccace/managementportal#1]
Please can update the documentation and cleanup the project.

Readme is the same of [fendesk](https://github.com/mitrefccace/fendesk) and many other files that i think can be deleted.

Thanks!

**Comment by CoachEd** [comment]
Thanks for your comment. We are looking to resolve this in a new version that is coming soon.

**Comment by CoachEd** [comment]
Thanks again for this issue. Extra files have been removed. README.md has been updated. A new release will be coming shortly.

**Comment by jampueroc** [comment]
Thanks @CoachEd.
We left others issues on [ACEDirect Main Project](https://github.com/FCC/ACEDirect/issues) if you can see please.

**Comment by CoachEd** [comment]
Thank you very much for the feedback. We are tracking.
